name: html5validator

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Checks HTML5
      id: action
      uses: Cyb3r-Jak3/html5validator-action@master
      with:
        config: ./.github/html5validator_config.yml
